#!/bin/sh

ACTION="$1"
AMOUNT="$2"

notify_vol() {
    vol="$(pamixer --get-volume)"
    dunstify -h string:x-dunst-stack-tag:volume \
             -h int:value:"$vol" \
             "Volume: $vol"
}

if [ "$ACTION" -eq 0 ]; then
    pamixer --toggle-mute
    mute="$(pamixer --get-mute)"

    if [ "$mute" = true ]; then
        dunstify -h string:x-dunst-stack-tag:volume \
                 -h int:value:0 \
                 "Volume: muted"
    else
        notify_vol
    fi

elif [ "$ACTION" -ge 1 ] && [ "$ACTION" -le 2 ] && \
     [ -n "$AMOUNT" ] && [ "$AMOUNT" -ge 1 ] && [ "$AMOUNT" -le 100 ]; then

    pamixer --unmute

    case "$ACTION" in
        1) pamixer --allow-boost --set-limit 150 -d "$AMOUNT" ;;
        2) pamixer --allow-boost --set-limit 150 -i "$AMOUNT" ;;
    esac

    notify_vol
fi

kill -42 $(pidof dwmblocks)
